[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "none"  # Disable Python build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
