name: Full Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        cd backend
        python -m pytest

  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install and Build
      env:
        VITE_GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        npm install
        npm run build

  deploy:
    needs: [backend-test, frontend-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Render
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_WEBHOOK }}
